sudo: required
services:
  - docker

script:
  - docker build -t mannydesigns/node .
  - docker images mannydesigns/node

before_deploy:
  - docker login -u singhakash1298  -p iitr1298a

deploy:
  provider: script
  script: docker push mannydesigns/node
  on:
    branch: master